version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}-frontend
    environment:
      NEXT_PUBLIC_API_ENDPOINT: https://api.d.ace2208.net
    ports:
      - '127.0.0.1:80:3000'
    restart: on-failure

  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}-backend
    environment:
      DATABASE_URL: mysql://root:${MYSQL_PASSWORD}@db-server-cluster.cluster-cvpoijg92k5y.ap-northeast-1.rds.amazonaws.com:3306/root
    ports:
      - '127.0.0.1:80:3001'
    restart: on-failure
