version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder
    image: ace-d-builder

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    image: ace-d-frontend
    restart: on-failure
    ports:
      - '127.0.0.1:3000:3000'
  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    image: ace-d-backend
    restart: on-failure
    ports:
      - '127.0.0.1:3001:3001'

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'root'
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
