version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    image: ace-d-frontend
    environment:
      NEXT_PUBLIC_API_ENDPOINT: http://backend:3001
    ports:
      - '3000:3000'
    restart: on-failure

  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    image: ace-d-backend
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/root
    ports:
      - '3001:3001'
    restart: on-failure

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'root'
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
