version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder
    image: ace-d-builder

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONT}

  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_API}
