version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    environment:
      NEXT_PUBLIC_API_ENDPOINT: http://backend:3001
    ports:
      - '127.0.0.1:3000:3000'
    restart: on-failure

  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/admin
    ports:
      - '127.0.0.1:3001:3001'
    restart: on-failure

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'admin'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
