version: '3.7'
services:
  builder:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: builder
    environment:
      - DOMAIN_LOCK=front.d.ace2208.net

  frontend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: frontend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONT}
    ports:
      - '80:3000'
    restart: on-failure

  backend:
    build:
      context: ../../..
      dockerfile: ./packages/infrastructure/docker/Dockerfile
      target: backend
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_API}
    ports:
      - '80:3001'
    restart: on-failure
