name: CI

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: yarn_cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.next
            ${{ steps.yarn_cache.outputs.dir }}
          key: ${{ runner.os }}-ci-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-ci-
      - run: yarn install --frozen-lockfile
      - run: yarn lint:check
      - run: yarn build
