name: Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - id: login
        uses: aws-actions/amazon-ecr-login@v1

      - id: build
        env:
          ECR_REGISTRY: ${{ steps.login.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          docker compose -f ./packages/infrastructure/docker/docker-compose.prod.yml build
          docker compose -f ./packages/infrastructure/docker/docker-compose.prod.yml push backend
          docker compose -f ./packages/infrastructure/docker/docker-compose.prod.yml push frontend

      - id: render_frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./packages/infrastructure/aws/task_definition.json
          container-name: frontend
          image: ${{ steps.login.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}-frontend:latest

      - id: render_backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./packages/infrastructure/aws/task_definition.json
          container-name: backend
          image: ${{ steps.login.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}-backend:latest

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render_frontend.outputs.task-definition }}
          service: api-ecs-service
          cluster: api-ecs-cluster

      - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render_backend.outputs.task-definition }}
          service: api-ecs-service
          cluster: api-ecs-cluster
