name: PR Check

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
jobs:
  ci:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pr-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-pr-node-modules-
      - run: yarn install --frozen-lockfile
      - run: |
          #!/bin/bash
          local_branch="$(git branch --show-current)"
          branch_regex="^feature\/[a-z0-9_]+$"

          if [ -z "$local_branch" ]; then
            local_branch="${{ github.head_ref }}"
          fi

          if [[ ! $local_branch =~ $branch_regex ]]; then
            echo "Invalid branch name: $local_branch"
            exit 1
          fi
      - run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: yarn lint:check
      - run: yarn build
